Rails:
  Enabled: true

AllCops:
  Include:
    - "**/*.gemspec"
    - "**/Rakefile"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"

StringLiterals:
  EnforcedStyle: double_quotes

PerlBackrefs:
  Enabled: false

SymbolProc:
  Exclude:
    - "app/admin/**/*"

AssignmentInCondition:
  Exclude:
    - "bin/spring"

HandleExceptions:
  Exclude:
    - "bin/rails"
    - "bin/rake"

LineLength:
  Max: 200

Documentation:
  Enabled: false
