AllCops:
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes:
    - db/schema.rb
    - db/migrate/*
    - db/seeds.rb

StringLiterals:
  EnforcedStyle: double_quotes

LineLength:
  Max: 150

Documentation:
  Enabled: false
