defaults: &defaults
  app_name: "Access Cal Server"
  app_server: "Development"
  default_url: "http://localhost:3000"
  aws_s3_region: "us-east-2"
  aws_s3_assets_url: "https://xxxxxxxxx.cloudfront.net/assets"
  google_analytics_tracking_id: "UA-54471373-x"
  no_reply_email: "no-reply@accesscal.com"
  support_email: "support@accesscal.com"
  errors_email: "errors@accesscal.com"
  feedback_email: "feedback@accesscal.com"
  transactions_email: "transactions@accesscal.com"
  redis_url: ENV["REDIS_URL"]

test:
  <<: *defaults
  app_server: "Test"
  google_analytics_tracking_id: "UA-54471373-x"
  redis_url: "redis://localhost:6379"

development:
  <<: *defaults
  app_server: "Development"
  google_analytics_tracking_id: "UA-54471373-x"

staging:
  <<: *defaults
  app_server: "Staging"
  default_url: "http://access-cal-server-staging.herokuapp.com"
  google_analytics_tracking_id: "UA-xxxxxx-x"

production:
  <<: *defaults
  app_server: "Production"
  default_url: "https://www.accesscal.com"
  google_analytics_tracking_id: "UA-xxxxxx-x"
