defaults: &defaults
  app_name: "Events Server"
  app_server: "Development"
  default_url: "http://localhost:3000"
  aws_s3_region: "us-west-2"
  aws_s3_assets_url: "https://d1avux5rw5y0rl.cloudfront.net/assets"
  google_analytics_tracking_id: "UA-54471373-x"
  no_reply_email: "no-reply@events.com"
  support_email: "support@events.com"
  errors_email: "errors@events.com"
  feedback_email: "feedback@events.com"
  transactions_email: "transactions@events.com"
  redis_url: ENV["REDIS_URL"]

test:
  <<: *defaults
  app_server: "Test"
  google_analytics_tracking_id: "UA-54471373-x"
  redis_url: "redis://localhost:6379"

development:
  <<: *defaults
  app_server: "Development"
  google_analytics_tracking_id: "UA-54471373-x"

staging:
  <<: *defaults
  app_server: "Staging"
  default_url: "http://staging.events-server.com"
  google_analytics_tracking_id: "UA-54471373-x"

production:
  <<: *defaults
  app_server: "Production"
  default_url: "https://www.events-server.com"
  google_analytics_tracking_id: "UA-54471373-x"
