development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: events-server_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  username: postgres
  database: events-server_test
